'use client';
import {useRef,useState} from 'react';
import {makeNativeSetup,mergeNativeResult} from '@/lib/native-tracking';
import type {TrackingDoc} from '@/lib/tracking';
export default function NativePanel({doc,videoId,filename,video,time,blocked,onImport,onBusyChange}:{doc:TrackingDoc;videoId:string;filename:string;video:HTMLVideoElement|null;time:number;blocked:boolean;onImport:(doc:TrackingDoc)=>void;onBusyChange:(busy:boolean)=>void}){
 const input=useRef<HTMLInputElement>(null),[seconds,setSeconds]=useState('10'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 function download(){try{if(!video?.videoWidth)throw Error('Wait for the video to load.');const setup=makeNativeSetup(doc,{id:videoId,filename,width:video.videoWidth,height:video.videoHeight,duration:video.duration},time,Number(seconds));const url=URL.createObjectURL(new Blob([JSON.stringify(setup,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='pitchiq-setup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Setup exported. Process the original MP4 with the native runner, then import its result. Keep this setup unchanged until import.');}catch(e){setStatus((e as Error).message);}}
 async function importResult(file:File){setBusy(true);onBusyChange(true);try{if(file.size>2000000)throw Error('Result is too large. Use a shorter segment.');const raw=JSON.parse(await file.text());if(video&&(raw.video?.width!==video.videoWidth||raw.video?.height!==video.videoHeight||Math.abs(raw.video?.duration-video.duration)>.5))throw Error('Result video dimensions or duration do not match.');const result=mergeNativeResult(doc,raw,videoId);onImport(result.document);setStatus(`Imported ${result.summary.processedSeconds.toFixed(1)} seconds, processed in ${result.summary.elapsedSeconds.toFixed(1)} seconds. ${result.summary.observed} observed boxes; ${result.summary.predicted} estimates. ${result.summary.stopReason} Review playback, then Save changes.`);}catch(e){setStatus((e as Error).message);}finally{setBusy(false);onBusyChange(false);if(input.current)input.current.value='';}}
 return <section className="panel"><h2>Native tracking · Norfair preview</h2><p>Label visible players and the ball on the starting frame. You can also add confirmed labels later in the segment for a goalkeeper’s first appearance or a substitution. The runner uses those labels when it reaches them.</p><p>Process 5–20 seconds on your computer, then bring the results back here. This is a separate Python runner; setup instructions are in <code>services/video/README.md</code> in GitHub.</p><label>Segment length <select value={seconds} onChange={e=>setSeconds(e.target.value)} disabled={blocked||busy}>{[5,10,20].map(s=><option key={s} value={s}>{s} seconds</option>)}</select></label><div className="tracking-save"><button className="button" disabled={blocked||busy||!video?.videoWidth} onClick={download}>1. Export native setup</button><button className="button" disabled={blocked||busy} onClick={()=>input.current?.click()}>2. Import native result</button><input ref={input} type="file" accept=".json,application/json" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void importResult(file);}}/></div><p role="status">{status||'Uncertain observations remain marked for review. Off-screen players do not need a box on every frame.'}</p></section>;
}
