import fs from 'node:fs';
import assert from 'node:assert/strict';
import {loadPyodide} from '../public/norfair/runtime/pyodide.mjs';
const runtime=await loadPyodide({indexURL:process.cwd()+'/public/norfair/runtime/'});
await runtime.loadPackage(['numpy','scipy','rich','pygments']);
for(const name of ['filterpy-1.4.5-py3-none-any.whl','norfair-2.3.0-py3-none-any.whl'])runtime.unpackArchive(new Uint8Array(fs.readFileSync('public/norfair/runtime/'+name)),'zip',{extractDir:'/lib/python3.12/site-packages'});
runtime.runPython(fs.readFileSync('public/norfair/engine.py','utf8'));
const fn=runtime.globals.get('process'),step=data=>JSON.parse(fn(JSON.stringify(data)));
const sample=(id,x,evidence='detection')=>({id,box:{x,y:.3,w:.02,h:.05},evidence});
let result=step({reset:true,width:1920,height:1080,active:['A1','B1'],samples:[sample('A1',.2),sample('B1',.8)]});
assert.equal(result.length,2);
for(let i=1;i<=10;i++)result=step({active:['A1','B1'],samples:[sample('A1',.2+i*.05),sample('B1',.8-i*.05)]});
assert.ok(result.find(p=>p.id==='A1').box.x>result.find(p=>p.id==='B1').box.x,'labelled identities survive crossing');
result=step({active:['A1'],samples:[sample('A1',.75,'predicted')]});
assert.equal(result.length,1);assert.equal(result[0].id,'A1');
result=step({active:['A1','A2'],clear:['A1'],samples:[sample('A1',.1),sample('A2',.9)]});
assert.ok(Math.abs(result.find(p=>p.id==='A1').box.x-.1)<1e-6,'correction resets old motion');
step({reset:true,width:1920,height:1080,active:['A1'],samples:[sample('A1',.2)]});
result=step({active:['A1'],samples:[sample('A1',.25,'predicted')],camera:{reliable:true,scale:1,dx:.05,dy:0}});
assert.ok(Math.abs(result[0].box.x-.25)<.001,'camera pan moves predicted box');
fn.destroy();console.log('PASS: actual browser Norfair runtime, crossings, removal, correction, camera compensation');
