const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const Module=require('node:module');
const ts=require('typescript');
const {DatabaseSync}=require('node:sqlite');
function load(file,overrides={}){const filename=path.resolve(file);const m=new Module(filename,module);m.paths=module.paths;const original=m.require.bind(m);m.require=(id)=>overrides[id]||original(id);m._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,filename);return m.exports;}
const tracking=load('lib/tracking.ts');
const tracker=load('lib/patch-tracker.ts');
const box={x:.3,y:.3,w:.06,h:.1};
function frame(dx=0,dy=0,visible=true){const width=160,height=100,data=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4;const target=visible&&x>=48+dx&&x<58+dx&&y>=30+dy&&y<40+dy;data[i]=target?220:35;data[i+1]=target?30:95;data[i+2]=target?25:40;data[i+3]=255;}return {width,height,data};}
test('appearance tracker follows translation and stops on disappearance',()=>{const seed=tracker.seedTrack(frame(),box,'A1');const next=tracker.advanceTrack(frame(3,2),seed);assert.ok(next.track);assert.ok(Math.abs(next.track.box.x-(box.x+3/160))<=1/160);assert.ok(Math.abs(next.track.box.y-(box.y+2/100))<=1/100);assert.equal(tracker.advanceTrack(frame(0,0,false),seed).track,undefined);});
test('roster intervals, re-entry, correction and frame gaps',()=>{let d=tracking.initialTracking();d.players.push({id:'sub',name:'Sub',number:'12',team:'A',starter:false});d.substitutions.push({id:'s1',time:10,off:'A1',on:'sub'},{id:'s2',time:20,off:'sub',on:'A1'});assert.ok(tracking.trackingSchema.safeParse(d).success);assert.equal(tracking.isActive(d,'A1',12),false);assert.equal(tracking.isActive(d,'A1',22),true);d.points=[{playerId:'A1',time:1,box,score:1,source:'manual',reviewed:true},{playerId:'A1',time:2,box,score:.9,source:'experimental',reviewed:false},{playerId:'A2',time:2,box,score:.9,source:'experimental',reviewed:false}];assert.equal(tracking.pointAt(d.points,'A1',1.5),undefined);const fixed=tracking.correctPoint(d,{...d.points[0],time:1.5});assert.equal(fixed.points.filter(p=>p.playerId==='A1'&&p.source==='experimental').length,0);assert.ok(fixed.points.some(p=>p.playerId==='A2'));d.points.push({...d.points[0],time:12});assert.equal(tracking.trackingSchema.safeParse(d).success,false);});
test('API owner isolation, round trip, revision conflicts and invalid writes',async()=>{const sql=new DatabaseSync(':memory:');sql.exec('CREATE TABLE records(id TEXT PRIMARY KEY,owner TEXT,kind TEXT,data TEXT,created INTEGER)');let owner='coach-a';const db={prepare:query=>({bind:(...args)=>({first:async()=>sql.prepare(query).get(...args)||null,run:async()=>({meta:{changes:Number(sql.prepare(query).run(...args).changes)}})})})};const api=load('app/api/tracking/route.ts',{'@/lib/tracking':tracking,'@/lib/server':{identity:async()=>{if(!owner)throw Error('Unauthorized');return owner;},db:()=>db,failure:e=>Response.json({error:e.message},{status:e.message==='Unauthorized'?401:503})}});const id='11111111-1111-4111-8111-111111111111';sql.prepare('INSERT INTO records VALUES(?,?,?,?,?)').run(id,'coach-a','video',JSON.stringify({filename:'test.mp4',metadata:{team:'Home',opponent:'Away'}}),1);const req=()=>new Request('https://test/api/tracking?videoId='+id);let response=await api.GET(req());assert.equal(response.status,200);const first=await response.json();assert.equal(first.revision,0);assert.equal(first.document.teamA,'Home');const post=(document,revision=0)=>api.POST(new Request('https://test/api/tracking',{method:'POST',body:JSON.stringify({videoId:id,revision,document})}));owner='coach-b';assert.equal((await api.GET(req())).status,404);assert.equal((await post(first.document)).status,404);owner='';assert.equal((await api.GET(req())).status,401);owner='coach-a';assert.equal((await post(first.document)).status,200);assert.equal((await post(first.document)).status,409);first.document.players[0].name='Saved Player';assert.equal((await post(first.document,1)).status,200);const saved=await (await api.GET(req())).json();assert.equal(saved.document.players[0].name,'Saved Player');assert.equal(saved.revision,2);assert.equal((await post({...first.document,points:[{playerId:'unknown',time:0,box,score:1,source:'manual',reviewed:true}]},2)).status,400);sql.close();});
const detector=load('lib/detection-core.ts');
test('detector decodes tiled coordinates, keeps ball separate and suppresses duplicates',()=>{const data=new Float32Array(3549*85),row=10*52+10,at=row*85;data[at]=.5;data[at+1]=.5;data[at+2]=Math.log(2);data[at+3]=Math.log(4);data[at+4]=.9;data[at+5]=.9;data[at+37]=.8;const found=detector.decodeYolox(data,{x:100,y:50,w:416,h:416},1000,600);assert.equal(found.length,2);assert.ok(Math.abs(found[0].box.x-.176)<1e-6);assert.equal(detector.suppress([...found,...found]).length,2);const rgba=new Uint8ClampedArray(416*416*4);rgba.set([12,34,56,255]);const input=detector.toTensor(rgba);assert.equal(input[0],56);assert.equal(input[416*416],34);assert.equal(input[416*416*2],12);});
test('detection matching preserves unique identities and stops ambiguous or missing tracks',()=>{const tr={id:'A1',box,kind:'person',vx:0,vy:0},d={id:'d',kind:'person',box:{...box,x:box.x+.005},score:.9};assert.ok(detector.associate([tr],[d])[0].detection);assert.equal(detector.associate([tr],[])[0].detection,undefined);assert.equal(detector.associate([tr],[{...d,kind:'ball'}])[0].detection,undefined);assert.ok(detector.associate([tr,{...tr,id:'A2'}],[d]).every(m=>!m.detection));assert.equal(detector.associate([tr],[d,{...d,id:'d2'}])[0].detection,undefined);});
test('accepted detector labels survive later corrections and schema round trips',()=>{let d=tracking.initialTracking();d.points=[{playerId:'A1',time:1,box,score:.8,source:'detector',reviewed:true},{playerId:'A1',time:2,box,score:.7,source:'experimental',reviewed:false},{playerId:'A1',time:3,box,score:.9,source:'detector',reviewed:true}];assert.ok(tracking.trackingSchema.safeParse(d).success);const next=tracking.correctPoint(d,{...d.points[0],time:1.5});assert.ok(next.points.some(p=>p.time===3&&p.source==='detector'));assert.ok(!next.points.some(p=>p.time===2));});
const vision=load('lib/track-vision.ts');
const persistent=load('lib/persistent-tracker.ts',{'./detection-core':detector,'./track-vision':vision});
const shirt=(bin)=>Array.from({length:14},(_,i)=>i===bin?1:0);
const person=(x=.3,appearance=shirt(1),score=.9)=>({id:'d',kind:'person',box:{...box,x},score,appearance});
test('persistent tracker recovers a short disappearance under the same identity',()=>{let tracks=[persistent.startTrack('A1','person',box,0,shirt(1))];let r=persistent.stepTracks(tracks,[],.2);assert.equal(r.tracks.length,1);assert.equal(r.samples[0].evidence,'predicted');assert.equal(r.issues.length,0);r=persistent.stepTracks(r.tracks,[person()],.4);assert.equal(r.samples[0].id,'A1');assert.equal(r.samples[0].recovered,true);assert.equal(r.samples[0].evidence,'detection');r=persistent.stepTracks(r.tracks,[],2);assert.equal(r.tracks.length,0);assert.equal(r.issues.length,1);});
test('weak detections may recover tracks but different shirt colors cannot steal them',()=>{const t=persistent.startTrack('A1','person',box,0,shirt(1));assert.equal(persistent.stepTracks([t],[person(.302,shirt(1),.15)],.2).samples[0].evidence,'detection');assert.equal(persistent.stepTracks([t],[person(.3,shirt(7))],.2).samples[0].evidence,'predicted');});
test('assignment is globally unique and ambiguous observations remain predictions',()=>{assert.deepEqual(persistent.assignMinimum([[.1,.2],[.15,.7]]),[1,0]);const tracks=[persistent.startTrack('A1','person',box,0,shirt(1)),persistent.startTrack('A2','person',box,0,shirt(1))];const result=persistent.stepTracks(tracks,[person()],.2);assert.ok(result.samples.every(s=>s.evidence==='predicted'));assert.equal(result.tracks.length,2);});
test('camera translation assists matching; scene cuts stop identity propagation',()=>{const t=persistent.startTrack('A1','person',box,0,shirt(1));const camera={scale:1,dx:.08,dy:0,reliable:true,cut:false};assert.equal(persistent.stepTracks([t],[person(.38)],.2,camera).samples[0].evidence,'detection');const cut=persistent.stepTracks([t],[person()],.2,{...camera,cut:true});assert.equal(cut.tracks.length,0);assert.match(cut.issues[0].reason,/camera cut/i);});
test('pitch filter removes spectators but falls back for non-green scenes',()=>{const width=160,height=90,data=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4;data.set(y>30?[50,125,40,255]:[140,140,140,255],i);}const mask=vision.pitchMask({width,height,data});assert.equal(mask.reliable,true);assert.equal(mask.contains({x:.4,y:.1,w:.02,h:.1}),false);assert.equal(mask.contains({x:.4,y:.5,w:.02,h:.1}),true);data.fill(120);assert.equal(vision.pitchMask({width,height,data}).reliable,false);});
test('estimated boxes are explicitly identified in saved tracking data',()=>{const d=tracking.initialTracking();d.points=[{playerId:'A1',time:.2,box,source:'experimental',score:.2,reviewed:false,evidence:'predicted'}];assert.ok(tracking.trackingSchema.safeParse(d).success);assert.equal(tracking.trackingSchema.parse(d).points[0].evidence,'predicted');});
test('camera estimator measures image translation and rejects an abrupt scene change',()=>{const width=320,height=180,a=new Uint8ClampedArray(width*height*4),b=new Uint8ClampedArray(a.length);let seed=43;for(let i=0;i<width*height;i++){seed=(seed*1664525+1013904223)>>>0;const value=(seed>>>16)%256;a.set([value,value,value,255],i*4);}for(let y=2;y<height;y++)for(let x=4;x<width;x++)b.set(a.subarray(((y-2)*width+x-4)*4,((y-2)*width+x-4)*4+4),(y*width+x)*4);const motion=vision.estimateCamera({width,height,data:a},{width,height,data:b});assert.equal(motion.reliable,true);assert.ok(Math.abs(motion.dx-4/width)<.004);assert.ok(Math.abs(motion.dy-2/height)<.004);a.fill(0);b.fill(255);assert.equal(vision.estimateCamera({width,height,data:a},{width,height,data:b}).cut,true);});
test('real professional-match replay improves short-pass continuity without hiding predictions',()=>{const fixture=JSON.parse(fs.readFileSync('tests/fixtures/pro-match-detections.json'));const frames=fixture.frames,seeds=frames[0].detections.filter(d=>fixture.seedIds.includes(d.id));let old=seeds.map(d=>({id:d.id,kind:d.kind,box:d.box,vx:0,vy:0})),current=seeds.map(d=>persistent.startTrack(d.id,d.kind,d.box,frames[0].time,d.appearance));let recoveries=0;for(const f of frames.slice(1)){old=detector.associate(old,f.detections.filter(d=>d.score>=.25)).filter(m=>m.detection).map(m=>m.track);const r=persistent.stepTracks(current,f.detections.filter(d=>d.pitch),f.time,f.camera);current=r.tracks;recoveries+=r.samples.filter(s=>s.recovered).length;assert.ok(r.samples.every(s=>['predicted','detection'].includes(s.evidence)));assert.equal(new Set(r.samples.map(s=>s.id)).size,r.samples.length);}assert.ok(current.length>old.length);assert.ok(recoveries>0);});
const ballTracker=load('lib/ball-tracker.ts',{'./track-vision':vision});
const recovery=load('lib/player-recovery.ts',{'./detection-core':detector,'./track-vision':vision,'./persistent-tracker':persistent});
function ballFrame(dx=0,visible=true,line=false){const width=320,height=180,data=new Uint8ClampedArray(width*height*4);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const white=visible&&(x-(100+dx))**2+(y-90)**2<=9||line&&x===150;data.set(white?[240,240,230,255]:[40,100,35,255],(y*width+x)*4);}return {width,height,data};}
test('dedicated ball tracker follows a small ball and excludes a long pitch line',()=>{const b={x:97/320,y:87/180,w:7/320,h:7/180};const seed=ballTracker.seedBall(ballFrame(),b,0);const r=ballTracker.advanceBall(ballFrame(5,true,true),seed,.1);assert.ok(r.sample);assert.equal(r.sample.evidence,'appearance');assert.ok(Math.abs(r.sample.box.x*320-101.5)<3);assert.equal(ballTracker.ballCandidates(ballFrame(0,false,true),b,100).length,0);assert.equal(ballTracker.advanceBall(ballFrame(0,false),seed,3.1).track,undefined);});
test('missing player recovery needs repeated compatible sightings and preserves identity',()=>{const t={...persistent.startTrack('A1','person',box,0,shirt(1)),team:'A'};let missing=[recovery.rememberPlayer(t,1.5)],r;for(const time of [1.6,1.8,2]){r=recovery.recoverPlayers([],missing,[person()],time,vision.stillCamera);missing=r.missing;if(time<2)assert.equal(r.restored.length,0);}assert.equal(r.restored[0].id,'A1');assert.equal(r.events.length,1);assert.equal(recovery.recoverPlayers([], [recovery.rememberPlayer(t,1.5)], [person(.3,shirt(7))],2,vision.stillCamera).restored.length,0);});
test('count and same entry edge alone cannot resolve a contested or stale identity',()=>{const a={...persistent.startTrack('A1','person',box,0,shirt(1)),team:'A'},b={...a,id:'A2'};let missing=[recovery.rememberPlayer(a,1.5),recovery.rememberPlayer(b,1.5)];for(const t of [1.6,1.8,2]){const r=recovery.recoverPlayers([],missing,[person()],t,vision.stillCamera);assert.equal(r.restored.length,0);missing=r.missing;}assert.equal(recovery.recoverPlayers([],missing,[person()],15,vision.stillCamera).missing.length,2);});
test('remaining roster suggestion requires unique team appearance evidence',()=>{const labelled=[...Array.from({length:10},()=>({team:'A',appearance:shirt(1)})),...Array.from({length:10},()=>({team:'B',appearance:shirt(7)}))],unlabelled=[{id:'A11',team:'A'}];assert.equal(recovery.remainingPlayerSuggestion('A',unlabelled,labelled,[person()]).playerId,'A11');assert.equal(recovery.remainingPlayerSuggestion('A',unlabelled,labelled,[person(),{...person(.5),id:'other'}]),undefined);assert.equal(recovery.remainingPlayerSuggestion('A',unlabelled,labelled,[person(.3,shirt(7))]),undefined);});
test('checkpoint and inferred evidence survive schema parsing',()=>{const d=tracking.initialTracking();d.checkpoint={start:2,time:7};d.points=[{playerId:'A1',time:7,box,score:.7,source:'experimental',reviewed:false,evidence:'reidentified'},{playerId:'ball',time:7,box,score:.7,source:'experimental',reviewed:false,evidence:'appearance'}];const parsed=tracking.trackingSchema.parse(d);assert.equal(parsed.checkpoint.time,7);assert.equal(parsed.points[0].evidence,'reidentified');assert.equal(parsed.points[1].evidence,'appearance');});
test('a distinctive keeper returns after a minute; same-kit identities remain remembered without guessing',()=>{
 const keeper={...persistent.startTrack('A1','person',{...box,x:.01},0,shirt(2)),team:'A'};
 const others=[{...persistent.startTrack('A2','person',{...box,x:.8},60,shirt(1)),team:'A'}];
 let missing=[recovery.rememberPlayer(keeper,1.5)],r;
 for(const t of [60,60.2,60.4,60.6,60.8]){r=recovery.recoverPlayers(others,missing,[person(.4,shirt(2))],t,vision.stillCamera);missing=r.missing;if(t<60.8)assert.equal(r.restored.length,0);}
 assert.equal(r.restored[0].id,'A1');
 const same={...keeper,id:'A3',appearance:shirt(1)};
 missing=[recovery.rememberPlayer(same,1.5)];
 for(const t of [60,60.2,60.4,60.6,60.8]){r=recovery.recoverPlayers(others,missing,[person(.4,shirt(1))],t,vision.stillCamera);missing=r.missing;assert.equal(r.restored.length,0);}
 assert.equal(missing.length,1);
 const d=tracking.initialTracking();d.playerMemory=recovery.savePlayerMemory([],missing);const parsed=tracking.trackingSchema.parse(d);
 assert.equal(parsed.playerMemory[0].playerId,'A3');assert.equal(recovery.restorePlayerMemory(parsed.playerMemory[0],'A',80).locationKnown,false);
 assert.equal(recovery.recoverPlayers([],missing,[],61,{...vision.stillCamera,cut:true}).missing.length,1);
});
test('a starter can first be labelled later without changing earlier labels or roster intervals',()=>{
 let d=tracking.initialTracking();d.points=[{playerId:'A1',time:0,box,score:1,source:'manual',reviewed:true}];
 d=tracking.correctPoint(d,{playerId:'B1',time:45,box,score:1,source:'manual',reviewed:true});
 assert.equal(tracking.pointAt(d.points,'B1',0),undefined);assert.equal(tracking.pointAt(d.points,'B1',45).playerId,'B1');assert.equal(d.substitutions.length,0);assert.ok(tracking.trackingSchema.safeParse(d).success);
});
const field=load('lib/field-reference.ts');
test('field marks on different frames follow a shared camera segment and never bridge a cut',()=>{
 const a={time:0,segment:'one',scale:1,dx:0,dy:0},b=field.advanceFieldCamera(a,1,{scale:1.1,dx:.1,dy:.02,reliable:true,cut:false});
 const mark={id:'c',name:'far-left',time:0,points:[{x:.2,y:.3}]};
 const projected=field.projectFieldMark(mark,1,[a,b]);assert.ok(Math.abs(projected.points[0].x-.32)<1e-8);assert.equal(projected.estimated,true);
 assert.equal(field.projectFieldMark(mark,2,[a,b,{...b,time:2,segment:'two'}]),undefined);
 assert.equal(field.advanceFieldCamera(a,1,{scale:1,dx:0,dy:0,reliable:false,cut:false}),undefined);
 const d=tracking.initialTracking();d.fieldMarks=[mark,{id:'l',name:'near-touchline',time:20,points:[{x:.1,y:.8},{x:.8,y:.8}]}];d.fieldCamera=[a,b];assert.equal(tracking.trackingSchema.parse(d).fieldMarks.length,2);
});
test('ball recovery searches around the last nearby player and needs repeated visual support',()=>{
 const b={x:97/320,y:87/180,w:7/320,h:7/180},seed={...ballTracker.seedBall(ballFrame(),b,0),time:.4,nearPlayer:{id:'A2',time:0},box:{...b,x:.8},vx:.1};
 const players=[{id:'A2',x:.31,y:.4,w:.02,h:.1}];
 const focus=ballTracker.ballSearchFocus(seed,.5,players);assert.ok(focus.x<.4);
 const first=ballTracker.advanceBall(ballFrame(5),seed,.5,vision.stillCamera,players);assert.ok(first.track);assert.equal(first.sample,undefined);
 const second=ballTracker.advanceBall(ballFrame(5),first.track,.6,vision.stillCamera,players);assert.equal(second.sample.evidence,'appearance');assert.equal(second.recovered,true);
 assert.equal(ballTracker.advanceBall(ballFrame(0,false),seed,3.2,vision.stillCamera,players).track,undefined);
});
test('neural ball recovery also requires repeated sightings and updates the nearby-player hint',()=>{
 const b={x:97/320,y:87/180,w:7/320,h:7/180},seed={...ballTracker.seedBall(ballFrame(),b,0),time:.3},d={box:b,score:.6},players=[{id:'A2',x:.30,y:.4,w:.03,h:.1}];
 const first=ballTracker.confirmBallDetection(ballFrame(),seed,d,.4,vision.stillCamera,players);assert.equal(first.sample,undefined);
 const second=ballTracker.confirmBallDetection(ballFrame(),first.track,d,.5,vision.stillCamera,players);assert.equal(second.sample.evidence,'appearance');assert.equal(second.track.nearPlayer.id,'A2');
});
