export const players = [
 {id:1,name:'Ethan Brooks',position:'GK',distance:4.2,number:1}, {id:2,name:'Noah Williams',position:'RB',distance:10.4,number:2}, {id:3,name:'Oliver Chen',position:'CB',distance:9.1,number:4}, {id:4,name:'Lucas Martinez',position:'CB',distance:9.4,number:5}, {id:5,name:'Liam Anderson',position:'LB',distance:10.6,number:3}, {id:6,name:'James Wilson',position:'CM',distance:11.8,number:8}, {id:7,name:'Mateo Silva',position:'DM',distance:10.9,number:6}, {id:8,name:'Leo Bennett',position:'CM',distance:11.2,number:10}, {id:9,name:'Daniel Wright',position:'RW',distance:10.7,number:7}, {id:10,name:'Alex Morgan',position:'ST',distance:9.8,number:9}, {id:11,name:'Sam Taylor',position:'LW',distance:10.3,number:11}];
export const events = [
 {id:'e1',time:762,type:'Build-up',title:'A patient build-up opens the right side',body:'Brooks finds Silva between the first pressing line. Wright holds the width, creating a passing lane into the final third.',confidence:92,player:7,tone:'green'},
 {id:'e2',time:1428,type:'Goal',title:'Third-man run creates the opening goal',body:'Bennett draws a midfielder before releasing Morgan into the box. A positive sequence to revisit with the attacking unit.',confidence:96,player:10,tone:'green'},
 {id:'e3',time:2538,type:'Defensive gap',title:'Space opens between the lines',body:'A potential 24 m gap separates midfield and defense after possession is lost. Silva is isolated as the opponent advances through the left half-space.',confidence:87,player:7,tone:'amber'},
 {id:'e4',time:3162,type:'Overload',title:'Right-side overload creates progression',body:'Williams, Wright and Wilson create a 3v2 on the right. Their rotation gives the ball carrier two forward options.',confidence:91,player:9,tone:'green'},
 {id:'e5',time:4062,type:'Marking',title:'Far-post runner arrives unmarked',body:'Wilson recovers toward the ball but may lose the far-post runner. Review the handover between midfield and the left back.',confidence:78,player:6,tone:'amber'},
 {id:'e6',time:4680,type:'High regain',title:'A coordinated press wins the ball back',body:'Morgan curves his press to block the central pass. Bennett steps forward and recovers possession in the attacking third.',confidence:89,player:8,tone:'green'}];
export const matches=[{opponent:'Cedar Valley FC',date:'Sep 20, 2026',score:'2 – 1',result:'W',possession:58},{opponent:'Park City United',date:'Sep 13, 2026',score:'1 – 1',result:'D',possession:54},{opponent:'Wasatch Athletic',date:'Sep 6, 2026',score:'3 – 0',result:'W',possession:61},{opponent:'Riverton SC',date:'Aug 30, 2026',score:'0 – 1',result:'L',possession:49},{opponent:'Summit FC',date:'Aug 23, 2026',score:'2 – 0',result:'W',possession:57}];
export const stamp=(s:number)=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
export const stages=['Queued','Detecting field','Detecting players and ball','Assigning teams','Tracking movement','Detecting events','Generating tactical insights','Ready for review'];
