import type {Box} from './tracking';
export type Detection={id:string;kind:'person'|'ball';score:number;box:Box};
export type Crop={x:number;y:number;w:number;h:number};
export const INPUT_SIZE=416;
export function iou(a:Box,b:Box){const area=Math.max(0,Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y));return area/(a.w*a.h+b.w*b.h-area||1);}
export function suppress(items:Detection[],threshold=.45){const out:Detection[]=[];for(const item of [...items].sort((a,b)=>b.score-a.score)){if(!out.some(other=>other.kind===item.kind&&iou(other.box,item.box)>threshold))out.push(item);}return out.slice(0,80);}
export function cropsFor(width:number,height:number,detailed:boolean):Crop[]{const full={x:0,y:0,w:width,h:height};if(!detailed||Math.max(width,height)<=512)return [full];const size=Math.min(512,Math.min(width,height)),step=Math.round(size*.8);const xs:number[]=[],ys:number[]=[];for(let x=0;;x+=step){xs.push(Math.min(x,width-size));if(x>=width-size)break;}for(let y=0;;y+=step){ys.push(Math.min(y,height-size));if(y>=height-size)break;}return [full,...ys.flatMap(y=>xs.map(x=>({x,y,w:size,h:size})))];}
// Official YOLOX ONNX export uses BGR values in [0,255], CHW, and top-left letterboxing.
export function toTensor(rgba:Uint8ClampedArray){const plane=INPUT_SIZE*INPUT_SIZE,out=new Float32Array(plane*3);for(let i=0;i<plane;i++){out[i]=rgba[i*4+2];out[plane+i]=rgba[i*4+1];out[plane*2+i]=rgba[i*4];}return out;}
export function decodeYolox(data:Float32Array,crop:Crop,width:number,height:number,minScore=.25){const items:Detection[]=[];const scale=Math.min(INPUT_SIZE/crop.w,INPUT_SIZE/crop.h);let row=0;for(const stride of [8,16,32]){const cells=INPUT_SIZE/stride;for(let gy=0;gy<cells;gy++)for(let gx=0;gx<cells;gx++,row++){const offset=row*85,objectness=data[offset+4];if(objectness<minScore)continue;for(const [cls,kind] of [[0,'person'],[32,'ball']] as const){const score=objectness*data[offset+5+cls];if(score<minScore)continue;const cx=(data[offset]+gx)*stride/scale,cy=(data[offset+1]+gy)*stride/scale,w=Math.exp(data[offset+2])*stride/scale,h=Math.exp(data[offset+3])*stride/scale;if(cx<0||cy<0||cx>crop.w||cy>crop.h)continue;const x1=Math.max(0,cx-w/2),y1=Math.max(0,cy-h/2),x2=Math.min(crop.w,cx+w/2),y2=Math.min(crop.h,cy+h/2);const box={x:(crop.x+x1)/width,y:(crop.y+y1)/height,w:(x2-x1)/width,h:(y2-y1)/height};if(box.w<.001||box.h<.001||!Number.isFinite(score))continue;items.push({id:'',kind,score,box});}}}return suppress(items);}
export type AssociationTrack={id:string;box:Box;kind:'person'|'ball';vx:number;vy:number};
// Conservative mutual best match. Ambiguous identities become gaps; no guessed re-entry.
export function associate(tracks:AssociationTrack[],detections:Detection[]){
 const center=(b:Box)=>({x:b.x+b.w/2,y:b.y+b.h/2});
 const candidates=tracks.map(tr=>{const p=center(tr.box);return detections.flatMap((d,index)=>{if(d.kind!==tr.kind)return [];const q=center(d.box),distance=Math.hypot(q.x-p.x-tr.vx,q.y-p.y-tr.vy);const gate=tr.kind==='ball'?.09:Math.max(.025,Math.min(.075,tr.box.h*1.8));const ratio=d.box.w*d.box.h/(tr.box.w*tr.box.h);if(distance>gate||ratio<.3||ratio>3.3)return [];return [{index,cost:distance/gate*.65+(1-iou({...tr.box,x:tr.box.x+tr.vx,y:tr.box.y+tr.vy},d.box))*.35}];}).sort((a,b)=>a.cost-b.cost);});
 const used=new Set<number>();return tracks.map((track,i)=>{const opts=candidates[i],best=opts[0];if(!best||best.cost>.83||opts[1]&&opts[1].cost-best.cost<.12)return {track,reason:'Detection missing or identity ambiguous. Confirm with a fresh box.'};if(candidates.some((other,j)=>j!==i&&other[0]?.index===best.index)||used.has(best.index))return {track,reason:'Two players could match the same box. Confirm their identities.'};used.add(best.index);const d=detections[best.index],a=center(track.box),b=center(d.box);return {track:{...track,box:d.box,vx:(b.x-a.x)*.7+track.vx*.3,vy:(b.y-a.y)*.7+track.vy*.3},detection:d};});
}
