import type {Box} from './tracking';
import {pitchMask,shirtFeature} from './track-vision';
import type {TrackDetection} from './persistent-tracker';
import {cropsFor,decodeYolox,suppress,toTensor,INPUT_SIZE,type Detection} from './detection-core';
import type {InferenceSession,Tensor} from 'onnxruntime-web';
let sessionPromise:Promise<InferenceSession>|undefined;
async function session(){if(!sessionPromise)sessionPromise=(async()=>{const ort=await import('onnxruntime-web/wasm');ort.env.wasm.numThreads=1;ort.env.wasm.proxy=false;ort.env.wasm.wasmPaths=new URL('/ort/',window.location.origin).href;const response=await fetch('/models/yolox-tiny.onnx',{signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error('Detector download failed. Reload and try again.');const bytes=await response.arrayBuffer();return ort.InferenceSession.create(bytes,{executionProviders:['wasm'],graphOptimizationLevel:'all'});})().catch(e=>{sessionPromise=undefined;throw e;});return sessionPromise;}
export async function detectFrame(source:HTMLVideoElement|HTMLCanvasElement,{detailed=true,minScore=.25,pitchOnly=true,focus,onProgress=()=>{},cancelled=()=>false}:{detailed?:boolean;minScore?:number;pitchOnly?:boolean;focus?:Box;onProgress?:(message:string)=>void;cancelled?:()=>boolean}={}):Promise<TrackDetection[]>{
 onProgress('Loading detector (first use downloads about 30 MB)…');const model=await session();if(cancelled())throw Error('Detection stopped.');const ort=await import('onnxruntime-web/wasm');const width='videoWidth'in source?source.videoWidth:source.width,height='videoHeight'in source?source.videoHeight:source.height;if(!width||!height)throw Error('Wait for the video frame to load.');const snapshot=document.createElement('canvas');const shrink=Math.min(1,1920/Math.max(width,height));snapshot.width=Math.round(width*shrink);snapshot.height=Math.round(height*shrink);snapshot.getContext('2d')!.drawImage(source,0,0,snapshot.width,snapshot.height);const scanWidth=snapshot.width,scanHeight=snapshot.height;const input=document.createElement('canvas');input.width=INPUT_SIZE;input.height=INPUT_SIZE;const ctx=input.getContext('2d',{willReadFrequently:true})!;const size=Math.min(256,scanWidth,scanHeight);const crops=focus?[{x:Math.max(0,Math.min(scanWidth-size,(focus.x+focus.w/2)*scanWidth-size/2)),y:Math.max(0,Math.min(scanHeight-size,(focus.y+focus.h/2)*scanHeight-size/2)),w:size,h:size}]:cropsFor(scanWidth,scanHeight,detailed),all:Detection[]=[];
 for(let i=0;i<crops.length;i++){if(cancelled())throw Error('Detection stopped.');onProgress(`Finding people and ball · area ${i+1}/${crops.length}`);const crop=crops[i],ratio=Math.min(INPUT_SIZE/crop.w,INPUT_SIZE/crop.h);ctx.fillStyle='rgb(114,114,114)';ctx.fillRect(0,0,INPUT_SIZE,INPUT_SIZE);ctx.drawImage(snapshot,crop.x,crop.y,crop.w,crop.h,0,0,Math.floor(crop.w*ratio),Math.floor(crop.h*ratio));const tensor=new ort.Tensor('float32',toTensor(ctx.getImageData(0,0,INPUT_SIZE,INPUT_SIZE).data),[1,3,INPUT_SIZE,INPUT_SIZE]);let output:Record<string,Tensor>|undefined;try{output=await model.run({[model.inputNames[0]]:tensor});const result=output[model.outputNames[0]];if(result.dims.join(',')!=='1,3549,85')throw Error('Unexpected detector output.');all.push(...decodeYolox(result.data as Float32Array,crop,scanWidth,scanHeight,minScore));}finally{tensor.dispose();if(output)Object.values(output).forEach(t=>t.dispose());}await new Promise(resolve=>setTimeout(resolve,0));}
 const frame=snapshot.getContext('2d')!.getImageData(0,0,scanWidth,scanHeight),mask=pitchMask(frame);
 if(pitchOnly&&!mask.reliable)onProgress('Pitch could not be isolated; showing all people for review.');
 return suppress(all).filter(d=>!focus||d.kind==='ball').filter(d=>!pitchOnly||mask.contains(d.box)).map((d,i)=>({...d,id:'candidate-'+(i+1),appearance:d.kind==='person'?shirtFeature(frame,d.box):[]}));
}
