import {identity,db,bucket,failure} from '@/lib/server';
import {stages} from '@/lib/demo';
export async function POST(request:Request){try{const owner=await identity();const action=new URL(request.url).searchParams.get('action');
 if(action==='init'){const body=await request.json() as any;const size=Number(body.size);if(!Number.isInteger(size)||size<1||size>100*1024*1024||typeof body.filename!=='string'||!body.filename.toLowerCase().endsWith('.mp4'))return Response.json({error:'Choose an MP4 under 100 MB.'},{status:400});const id=crypto.randomUUID();const key=owner+'/'+id;const upload=await bucket().createMultipartUpload(key,{httpMetadata:{contentType:'video/mp4'}});return Response.json({id,key,uploadId:upload.uploadId,partSize:4*1024*1024});}
 if(action==='complete'){const body=await request.json() as any;const id=String(body.id||''),key=String(body.key||'');if(!id||!key||!key.startsWith(owner+'/')||!Array.isArray(body.parts)||body.parts.length<1||body.parts.length>25)return Response.json({error:'Invalid upload completion.'},{status:400});const upload=await bucket().resumeMultipartUpload(key,String(body.uploadId||''));await upload.complete(body.parts.map((p:any)=>({partNumber:Number(p.partNumber),etag:String(p.etag)})));const data={filename:String(body.filename),key,metadata:body.metadata||{},started:Date.now(),mode:'manual'};await db().prepare('INSERT INTO records (id,owner,kind,data,created) VALUES (?,?,?,?,?)').bind(id,owner,'video',JSON.stringify(data),Date.now()).run();return Response.json({id,...data});}
 const size=Number(request.headers.get('content-length'));if(size>100*1024*1024)return Response.json({error:'MVP uploads are limited to 100 MB. Use a shorter MP4 excerpt.'},{status:413});const form=await request.formData();const f=form.get('file') as File; if(!f||!f.name?.toLowerCase().endsWith('.mp4')||f.size>100*1024*1024)return Response.json({error:'Choose an MP4 under 100 MB.'},{status:400});const id=crypto.randomUUID();const key=owner+'/'+id;const data={filename:f.name,key,metadata:JSON.parse(String(form.get('metadata')||'{}')),started:Date.now(),mode:'manual'};await bucket().put(key,f.stream(),{httpMetadata:{contentType:'video/mp4'}});try{await db().prepare('INSERT INTO records (id,owner,kind,data,created) VALUES (?,?,?,?,?)').bind(id,owner,'video',JSON.stringify(data),Date.now()).run();}catch(e){await bucket().delete(key);throw e;}return Response.json({id,...data});}catch(e){return failure(e);}}
export async function GET(request:Request){try{const owner=await identity();const url=new URL(request.url);const id=url.searchParams.get('id');const row=await db().prepare('SELECT data FROM records WHERE id=? AND owner=? AND kind=?').bind(id,owner,'video').first<{data:string}>();if(!row)return new Response('Not found',{status:404});const data=JSON.parse(row.data);if(url.searchParams.has('status')){const step=Math.min(7,Math.floor((Date.now()-data.started)/2500));return Response.json({step,stage:stages[step],mode:'manual'});}const obj=await bucket().get(data.key,{range:request.headers});if(!obj)return new Response('Not found',{status:404});const headers=new Headers({'Content-Type':'video/mp4','Accept-Ranges':'bytes','Cache-Control':'private, no-store'});if(obj.range&&'offset' in obj.range){const start=obj.range.offset??0;const length=obj.range.length??obj.size;headers.set('Content-Range',`bytes ${start}-${start+length-1}/${obj.size}`);headers.set('Content-Length',String(length));return new Response(obj.body,{status:206,headers});}headers.set('Content-Length',String(obj.size));return new Response(obj.body,{headers});}catch(e){return failure(e);}}
export async function DELETE(request:Request){try{const owner=await identity();const {id}=await request.json() as any;const row=await db().prepare('SELECT data FROM records WHERE id=? AND owner=? AND kind=?').bind(id,owner,'video').first<{data:string}>();if(row)await bucket().delete(JSON.parse(row.data).key);await db().batch([db().prepare('DELETE FROM records WHERE id=? AND owner=? AND kind=?').bind(id,owner,'video'),db().prepare('DELETE FROM records WHERE id=? AND owner=? AND kind=?').bind(owner+':tracking:'+id,owner,'tracking')]);return Response.json({deleted:true});}catch(e){return failure(e);}}
export async function PUT(request:Request){try{const owner=await identity();const url=new URL(request.url);if(url.searchParams.get('action')!=='part')return Response.json({error:'Invalid upload action.'},{status:400});const key=url.searchParams.get('key')||'',uploadId=url.searchParams.get('uploadId')||'',partNumber=Number(url.searchParams.get('partNumber'));if(!key.startsWith(owner+'/')||!uploadId||!Number.isInteger(partNumber)||partNumber<1||partNumber>25||!request.body)return Response.json({error:'Invalid upload part.'},{status:400});const result=await bucket().resumeMultipartUpload(key,uploadId).uploadPart(partNumber,request.body);return Response.json({etag:result.etag,partNumber});}catch(e){return failure(e);}}
